//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class joinRequests
    {
        public int id { get; set; }
        public int userId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> regularTravelId { get; set; }
        public Nullable<int> temporaryTravelId { get; set; }
    
        public virtual regularTraveling regularTraveling { get; set; }
        public virtual user user { get; set; }
    }
}
