//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class car_projectEntities : DbContext
    {
        public car_projectEntities()
            : base("name=car_projectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<car> car { get; set; }
        public virtual DbSet<gender> gender { get; set; }
        public virtual DbSet<joinRequests> joinRequests { get; set; }
        public virtual DbSet<messages> messages { get; set; }
        public virtual DbSet<regularTraveling> regularTraveling { get; set; }
        public virtual DbSet<travellerInRegularTravel> travellerInRegularTravel { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
