//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class regularTraveling
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public regularTraveling()
        {
            this.travellerInRegularTravel = new HashSet<travellerInRegularTravel>();
            this.joinRequests = new HashSet<joinRequests>();
        }
    
        public int id { get; set; }
        public Nullable<int> driverId { get; set; }
        public string source { get; set; }
        public string destination { get; set; }
        public Nullable<System.TimeSpan> exitTime { get; set; }
        public Nullable<System.TimeSpan> arriveTime { get; set; }
        public Nullable<int> day { get; set; }
        public Nullable<decimal> latSourcr { get; set; }
        public Nullable<decimal> longSource { get; set; }
        public Nullable<decimal> latDestination { get; set; }
        public Nullable<decimal> longDestination { get; set; }
    
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<travellerInRegularTravel> travellerInRegularTravel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<joinRequests> joinRequests { get; set; }
    }
}
