//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class temporaryTraveling
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public temporaryTraveling()
        {
            this.joinRequests = new HashSet<joinRequests>();
            this.temporaryTraveller = new HashSet<temporaryTraveller>();
        }
    
        public int id { get; set; }
        public Nullable<int> driverId { get; set; }
        public string source { get; set; }
        public string destination { get; set; }
        public Nullable<System.TimeSpan> exitTime { get; set; }
        public Nullable<System.TimeSpan> arriveTime { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<joinRequests> joinRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<temporaryTraveller> temporaryTraveller { get; set; }
    }
}
