//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class temporaryTraveller
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> travelId { get; set; }
        public Nullable<int> travellerId { get; set; }
        public string collectionPoint { get; set; }
        public string destinationPoint { get; set; }
        public Nullable<bool> isRegular { get; set; }
    
        public virtual user user { get; set; }
        public virtual temporaryTraveling temporaryTraveling { get; set; }
    }
}
