//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class travellerInRegularTravel
    {
        public int id { get; set; }
        public Nullable<int> regularTravelingId { get; set; }
        public Nullable<int> travelerId { get; set; }
        public string collectingPoint { get; set; }
        public string destinationPoint { get; set; }
        public Nullable<double> latCollection { get; set; }
        public Nullable<double> lngCollection { get; set; }
        public Nullable<double> latDestination { get; set; }
        public Nullable<double> lngDestination { get; set; }
    
        public virtual regularTraveling regularTraveling { get; set; }
        public virtual user user { get; set; }
    }
}
